# Generated by Django 5.0.7 on 2024-07-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profilemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="description",
            field=models.TextField(max_length=400),
        ),
    ]
