# Generated by Django 4.2.15 on 2024-08-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_pageseenmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pageseenmodel",
            name="browser",
        ),
    ]
