# Generated by Django 4.2.15 on 2024-08-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_pageseenmodel_csrf_coockie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pageseenmodel",
            old_name="csrf_coockie",
            new_name="session_key",
        ),
    ]
