# Generated by Django 5.0.7 on 2024-07-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todomodel",
            name="level",
            field=models.CharField(
                choices=[
                    ("green", "green"),
                    ("orange", "orange"),
                    ("red", "red"),
                ],
                default="easy",
                max_length=10,
            ),
        ),
    ]
