# Generated by Django 5.0.7 on 2024-07-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_todomodel_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todomodel",
            name="level",
            field=models.CharField(
                choices=[
                    ("green", "easy"),
                    ("orange", "medium"),
                    ("red", "hard"),
                ],
                default="easy",
                max_length=10,
            ),
        ),
    ]
