# Generated by Django 5.0.7 on 2024-07-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todomodel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='dead_end',
            field=models.DateField(),
        ),
    ]
